const Menu = [
  {
    num: 1,
    category: "hurbs",
    name: "Aloevera",
    image: "images/hurbs/aloe.jpg",
  },
  {
    num: 2,
    category: "hurbs",
    name: "Mint",
    image: "images/hurbs/mint.jfif",
  },
  {
    num: 3,
    category: "hurbs",
    name: "Tulsi",
    image: "images/hurbs/tulsi.jpg",
  },
  {
    num: 4,
    category: "Flowers",
    name: "Rose",
    image: "images/flower/rose.jfif",
  },
  {
    num: 5,
    category: "Flowers",
    name: "Lotus",
    image: "images/flower/lotus.jfif",
  },
  {
    num: 6,
    category: "Flowers",
    name: "Dhatura",
    image: "images/flower/dhatura.jfif",
  },
  {
    num: 7,
    category: "Flowers",
    name: "Hibiscus",
    image: "images/flower/hibiscus.jfif",
  },
  {
    num: 8,
    category: "Flowers",
    name: "MarieGold",
    image: "images/flower/mariegold.jfif",
  },
  {
    num: 9,
    category: "Fruits",
    name: "Strawberry",
    image: "images/fruit/strawberry.webp",
  },
  {
    num: 10,
    category: "Fruits",
    name: "Apple",
    image: "images/fruit/apple.jfif",
  },
  {
    num: 11,
    category: "Fruits",
    name: "Banana",
    image: "images/fruit/banana.jfif",
  },
  {
    num: 12,
    category: "Fruits",
    name: "Watermelon",
    image: "images/fruit/watermelon.jfif",
  },
  {
    num: 13,
    category: "Fruits",
    name: "Mango",
    image: "images/fruit/mango.webp",
  },
  {
    num: 14,
    category: "Fruits",
    name: "Orange",
    image: "images/fruit/orange.jpg",
  },
  {
    num: 15,
    category: "Fruits",
    name: "Coconut",
    image: "images/fruit/coconut.jpg",
  },
  {
    num: 16,
    category: "Vegetables",
    name: "Potato",
    image: "images/vegetable/potato.jfif",
  },
  {
    num: 17,
    category: "Vegetables",
    name: "Tomato",
    image: "images/vegetable/tomato.jpg",
  },
  {
    num: 18,
    category: "Vegetables",
    name: "LadyFinger",
    image: "images/vegetable/ladyfinger.jpg",
  },
  {
    num: 19,
    category: "Vegetables",
    name: "Flower",
    image: "images/vegetable/flower.jfif",
  },
  {
    num: 20,
    category: "Vegetables",
    name: "Vanguuu",
    image: "images/vegetable/vanga.jfif",
  },
  {
    num: 21,
    category: "Vegetables",
    name: "Lemon",
    image: "images/vegetable/lemon.jfif",
  },
];
export default Menu;
